name: smartstart
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

# Icon configuration for flutter_launcher_icons
flutter_icons:
  android: true
  image_path: "assets/icon_logo.png"

# The following section is specific to Flutter packages.
flutter:
  # Ensures Material Icons font is included
  uses-material-design: true

  # Add image assets here
  assets:
    - assets/images/
    - assets/images/animals/
    - assets/images/body_parts/
    - assets/images/alphabets/
    - assets/images/numbers/
    - assets/sounds/landing/l_eng
    - assets/sounds/landing/l_tag

  # To add custom fonts to your application, uncomment and update this section:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# For more details:
# Dart pubspec: https://dart.dev/tools/pub/pubspec
# Flutter assets: https://flutter.dev/docs/development/ui/assets
# Flutter fonts: https://flutter.dev/docs/cookbook/design/fonts
# flutter_launcher_icons: https://pub.dev/packages/flutter_launcher_icons
